name: Try to create a release
on: 
  workflow_call:
    secrets:
      GH_TOKEN:
jobs:
  create_release:
    name: Create a release
    runs-on: ubuntu-latest
    steps:
      - name: Make a stub file
        run: |
          echo "This is a stub file" > stub.txt
      - name: Create a release
        env:
          # GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          # GH_TOKEN: "${{ github.token }}"
          GH_TOKEN: "${{ secrets.GH_TOKEN }}"
          REPO: "${{ github.repository }}"
        run: |
          set +e
          # don't exit on error
          gh release create -R "${REPO}" test-release --notes "Release from GitHub Actions"
          set -e

          gh release upload -R "${REPO}" test-release stub.txt